<a href="https://colab.research.google.com/github/easuck/Asonov-MIB-001-ML/blob/main/Asonov_06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.__version__

'1.21.6'

2) Создать нулевой вектор размера 10

In [ ]:
import numpy as np
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
import numpy as np
np.full((1,7), 7)

array([[7, 7, 7, 7, 7, 7, 7]])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
import numpy as np
np.linspace(10,100,46)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
import numpy as np
arr = np.random.rand(5)
print(arr)
arr[::-1]

[0.78850271 0.44862345 0.81284369 0.335589   0.74033052]


array([0.74033052, 0.335589  , 0.81284369, 0.44862345, 0.78850271])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
arr = np.full((4,4),7)
arr[0,0] = 1
arr[1,1] = 2
arr[2,2] = 3
arr[3,3] = 4
print(arr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
arr = np.random.randint(0,10,size=(10,10))
print(arr)
arr - arr.mean(axis=1, keepdims = True)

[[7 5 0 4 1 0 3 4 9 3]
 [2 5 7 7 3 9 7 2 7 2]
 [1 9 1 4 9 5 7 9 6 7]
 [4 9 7 2 8 1 0 3 6 1]
 [1 5 8 5 4 1 2 5 2 8]
 [1 3 4 0 7 4 3 7 2 6]
 [2 1 3 6 0 1 1 6 8 7]
 [2 1 3 9 4 1 0 5 9 7]
 [3 0 1 9 5 1 8 1 8 8]
 [5 1 2 8 9 5 1 5 7 2]]


array([[ 3.4,  1.4, -3.6,  0.4, -2.6, -3.6, -0.6,  0.4,  5.4, -0.6],
       [-3.1, -0.1,  1.9,  1.9, -2.1,  3.9,  1.9, -3.1,  1.9, -3.1],
       [-4.8,  3.2, -4.8, -1.8,  3.2, -0.8,  1.2,  3.2,  0.2,  1.2],
       [-0.1,  4.9,  2.9, -2.1,  3.9, -3.1, -4.1, -1.1,  1.9, -3.1],
       [-3.1,  0.9,  3.9,  0.9, -0.1, -3.1, -2.1,  0.9, -2.1,  3.9],
       [-2.7, -0.7,  0.3, -3.7,  3.3,  0.3, -0.7,  3.3, -1.7,  2.3],
       [-1.5, -2.5, -0.5,  2.5, -3.5, -2.5, -2.5,  2.5,  4.5,  3.5],
       [-2.1, -3.1, -1.1,  4.9, -0.1, -3.1, -4.1,  0.9,  4.9,  2.9],
       [-1.4, -4.4, -3.4,  4.6,  0.6, -3.4,  3.6, -3.4,  3.6,  3.6],
       [ 0.5, -3.5, -2.5,  3.5,  4.5,  0.5, -3.5,  0.5,  2.5, -2.5]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
arr = np.random.randint(0,10,size=(10,10))
print(arr)
arr - np.median(arr, axis=0, keepdims = True)

[[2 4 1 0 3 2 8 5 6 4]
 [1 1 0 6 0 3 7 5 5 8]
 [9 9 8 5 1 9 3 0 6 8]
 [7 7 0 6 5 8 2 9 1 3]
 [8 2 9 7 0 6 2 4 5 4]
 [2 4 7 1 7 5 8 4 2 0]
 [9 0 3 3 0 2 1 5 5 1]
 [1 5 0 6 8 1 6 2 0 7]
 [9 7 8 3 2 4 8 4 7 2]
 [9 0 5 0 5 3 9 0 2 5]]


array([[-5.5,  0. , -3. , -4. ,  0.5, -1.5,  1.5,  1. ,  1. ,  0. ],
       [-6.5, -3. , -4. ,  2. , -2.5, -0.5,  0.5,  1. ,  0. ,  4. ],
       [ 1.5,  5. ,  4. ,  1. , -1.5,  5.5, -3.5, -4. ,  1. ,  4. ],
       [-0.5,  3. , -4. ,  2. ,  2.5,  4.5, -4.5,  5. , -4. , -1. ],
       [ 0.5, -2. ,  5. ,  3. , -2.5,  2.5, -4.5,  0. ,  0. ,  0. ],
       [-5.5,  0. ,  3. , -3. ,  4.5,  1.5,  1.5,  0. , -3. , -4. ],
       [ 1.5, -4. , -1. , -1. , -2.5, -1.5, -5.5,  1. ,  0. , -3. ],
       [-6.5,  1. , -4. ,  2. ,  5.5, -2.5, -0.5, -2. , -5. ,  3. ],
       [ 1.5,  3. ,  4. , -1. , -0.5,  0.5,  1.5,  0. ,  2. , -2. ],
       [ 1.5, -4. ,  1. , -4. ,  2.5, -0.5,  2.5, -4. , -3. ,  1. ]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
arr = np.random.randint(0,10,(5,5))
print(arr)
arrMax = np.amax(arr, axis = 1, keepdims = True)
print(arrMax)
arrMin = np.amin(arr, axis = 1, keepdims = True)
print(arrMin)
arr2 = np.concatenate((arr, arrMax, arrMin), axis = 1)
print(arr2)

[[5 3 0 3 6]
 [9 4 6 8 4]
 [1 4 1 5 1]
 [2 2 7 4 2]
 [1 7 9 4 6]]
[[6]
 [9]
 [5]
 [7]
 [9]]
[[0]
 [4]
 [1]
 [2]
 [1]]
[[5 3 0 3 6 6 0]
 [9 4 6 8 4 9 4]
 [1 4 1 5 1 5 1]
 [2 2 7 4 2 7 2]
 [1 7 9 4 6 9 1]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
arr = np.arange(1,51)
odd = arr[arr % 2 != 0].reshape((5,5))
even = arr[arr % 2 != 1].reshape((5,5))
print(odd)
print(even)
m = np.matmul(odd,even)
print(m)
#np.linalg.inv(m)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [ ]:
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
